/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.AccesoAleatorio;
import clases.Conexion;
import clases.Idioma;
import clases.Persona;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author bruiz9
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Connection cn = null;
    Statement stmt = null;

    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbPrimernomb = new javax.swing.JLabel();
        lbSegundonomb = new javax.swing.JLabel();
        lbPrimerape = new javax.swing.JLabel();
        lbSegundoape = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        cmbCalle = new javax.swing.JComboBox<>();
        txtDirC = new javax.swing.JTextField();
        cmbDirLetra = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtDirNo1 = new javax.swing.JTextField();
        txtDirNo2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        lbDatosPersonales = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbCarrera = new javax.swing.JLabel();
        lbSemestre = new javax.swing.JLabel();
        lbIngles = new javax.swing.JLabel();
        lbHorario = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        slNivelIng = new javax.swing.JSlider();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        lbDatosAcademicos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbArchivo = new javax.swing.JLabel();
        lbAcceso = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        cmbAcceso = new javax.swing.JComboBox<>();
        lbParametros = new javax.swing.JLabel();
        cmdAlmacenar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdResetar = new javax.swing.JButton();
        cmdVerPersonas = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbLookandfeel = new javax.swing.JLabel();
        lbCletra = new javax.swing.JLabel();
        lbCtextfield = new javax.swing.JLabel();
        lbIdioma = new javax.swing.JLabel();
        cmbIdioma = new javax.swing.JComboBox<>();
        cmbColorTextField = new javax.swing.JComboBox<>();
        cmbColorLetra = new javax.swing.JComboBox<>();
        cmdEstablecer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 0, 0));
        lbTitulo.setText("PROCESO DE MATRICULACIÓN");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCodigo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbCodigo.setText("Codigo: ");
        jPanel2.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lbPrimernomb.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbPrimernomb.setText("Primer Nombre:");
        jPanel2.add(lbPrimernomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lbSegundonomb.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbSegundonomb.setText("Segundo Nombre:");
        jPanel2.add(lbSegundonomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lbPrimerape.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbPrimerape.setText("Primer Apellido: ");
        jPanel2.add(lbPrimerape, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lbSegundoape.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbSegundoape.setText("Segundo Apellido: ");
        jPanel2.add(lbSegundoape, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbDireccion.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbDireccion.setText("Dirección:");
        jPanel2.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lbEmail.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbEmail.setText("Email: ");
        jPanel2.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        lbFecha.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbFecha.setText("Fecha Nacimiento: ");
        jPanel2.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lbSexo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbSexo.setText("Sexo:");
        jPanel2.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        txtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimerNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, -1));

        txtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundoNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        txtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimerApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        txtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundoApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        cmbCalle.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbCalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kr", "Cl", "Tv" }));
        jPanel2.add(cmbCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txtDirC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirCKeyTyped(evt);
            }
        });
        jPanel2.add(txtDirC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 30, -1));

        cmbDirLetra.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbDirLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L" }));
        jPanel2.add(cmbDirLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel11.setText("No.");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        txtDirNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirNo1KeyTyped(evt);
            }
        });
        jPanel2.add(txtDirNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 30, -1));

        txtDirNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirNo2KeyTyped(evt);
            }
        });
        jPanel2.add(txtDirNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 30, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText(" -");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 20, 30));

        txtEmail.setToolTipText("");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, -1));

        txtDia.setText("DD");
        txtDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaMouseClicked(evt);
            }
        });
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 30, -1));

        txtMes.setText("MM");
        txtMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesMouseClicked(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        jPanel2.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 30, -1));

        txtAño.setText("AAAA");
        txtAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAñoMouseClicked(evt);
            }
        });
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });
        jPanel2.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText(" /");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 20, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText(" /");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 20, 30));

        rbSexo.add(rbMasculino);
        rbMasculino.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        rbMasculino.setText("Masculino");
        jPanel2.add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, 30));

        rbSexo.add(rbFemenino);
        rbFemenino.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        rbFemenino.setText("Femenino");
        jPanel2.add(rbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, 30));

        rbSexo.add(rbOtro);
        rbOtro.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        rbOtro.setText("Otro");
        jPanel2.add(rbOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, -1));

        lbDatosPersonales.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbDatosPersonales.setText("Datos Personales");
        jPanel2.add(lbDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 380, 400));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCarrera.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbCarrera.setText("Carrera:");
        jPanel3.add(lbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lbSemestre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbSemestre.setText("Semestre:");
        jPanel3.add(lbSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lbIngles.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbIngles.setText("Nivel de Ingles:");
        jPanel3.add(lbIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lbHorario.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbHorario.setText("Horario Deseado:");
        jPanel3.add(lbHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cmbCarrera.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administración Ambiental", "Administración de Empresas", "Administración de Servicios de Salud", "Arquitectura", "Banca y Finanzas", "Comunicación Social", "Contaduría Pública", "Derecho", "Ingeniería Ambiental", "Ingeniería Agroindrustrial", "Ingeniería Civil", "Ingeniería de Sistemas", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Licenciatura en Educación Básica Primaria", "Mercadeo y Publicidad", "Negocios Internacionales", "Psicología" }));
        jPanel3.add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 310, -1));

        jSpinner1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));

        slNivelIng.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        slNivelIng.setMajorTickSpacing(10);
        slNivelIng.setPaintLabels(true);
        slNivelIng.setPaintTicks(true);
        slNivelIng.setValue(0);
        slNivelIng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(slNivelIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 270, 50));

        jCheckBox1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox1.setText("Lunes");
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 20));

        jCheckBox2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox2.setText("Martes");
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        jCheckBox3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox3.setText("Miercoles");
        jPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 20));

        jCheckBox4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox4.setText("Jueves");
        jPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 20));

        jCheckBox5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox5.setText("Viernes");
        jPanel3.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 20));

        jCheckBox6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jCheckBox6.setText("Sabado");
        jPanel3.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 20));

        lbDatosAcademicos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbDatosAcademicos.setText("Datos Académicos");
        jPanel3.add(lbDatosAcademicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 440, 320));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbArchivo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbArchivo.setText("Archivo:");
        jPanel5.add(lbArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        lbAcceso.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbAcceso.setText("Tipo de Acceso:");
        jPanel5.add(lbAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        jPanel5.add(txtArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, -1));

        cmbAcceso.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secuencial", "Aleatorio", "Relacional" }));
        cmbAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(cmbAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));

        lbParametros.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbParametros.setText("Parámetros");
        jPanel5.add(lbParametros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        cmdAlmacenar.setBackground(new java.awt.Color(204, 255, 255));
        cmdAlmacenar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmdAlmacenar.setForeground(new java.awt.Color(204, 0, 0));
        cmdAlmacenar.setText("Almacenar");
        cmdAlmacenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAlmacenarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdAlmacenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        cmdCancelar.setBackground(new java.awt.Color(204, 255, 255));
        cmdCancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmdCancelar.setForeground(new java.awt.Color(204, 0, 0));
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, 40));

        cmdResetar.setBackground(new java.awt.Color(204, 255, 255));
        cmdResetar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmdResetar.setForeground(new java.awt.Color(204, 0, 0));
        cmdResetar.setText("Resetear");
        cmdResetar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdResetar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 150, 40));

        cmdVerPersonas.setBackground(new java.awt.Color(204, 255, 255));
        cmdVerPersonas.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmdVerPersonas.setForeground(new java.awt.Color(204, 0, 0));
        cmdVerPersonas.setText("Ver Persona");
        cmdVerPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdVerPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerPersonasActionPerformed(evt);
            }
        });
        jPanel5.add(cmdVerPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 440, 290));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLookandfeel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbLookandfeel.setText("Look and Feel:");
        jPanel6.add(lbLookandfeel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lbCletra.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbCletra.setText("Color de Letra:");
        jPanel6.add(lbCletra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, -1));

        lbCtextfield.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbCtextfield.setText("Color TextField:");
        jPanel6.add(lbCtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        lbIdioma.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lbIdioma.setText("Idioma:");
        jPanel6.add(lbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        cmbIdioma.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        cmbIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(cmbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, -1));

        cmbColorTextField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbColorTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Amarillo", "Azul", "Rojo", "Rosa", "Verde", "Naranja", "Blanco" }));
        cmbColorTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(cmbColorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, -1));

        cmbColorLetra.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        cmbColorLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Amarillo", "Azul", "Rojo", "Rosa", "Verde", "Naranja", "Blanco" }));
        cmbColorLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(cmbColorLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, -1));

        cmdEstablecer.setBackground(new java.awt.Color(204, 255, 255));
        cmdEstablecer.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmdEstablecer.setForeground(new java.awt.Color(204, 0, 0));
        cmdEstablecer.setText("Establecer");
        cmdEstablecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEstablecerActionPerformed(evt);
            }
        });
        jPanel6.add(cmdEstablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 380, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(928, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        int p;
        p = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?");
        if (p == 0) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_cmdCancelarActionPerformed
    public void resetear() {
        txtCodigo.setText("");
        txtPrimerNombre.setText("");
        txtSegundoNombre.setText("");
        txtPrimerApellido.setText("");
        txtSegundoApellido.setText("");
        cmbCalle.setSelectedIndex(0);
        txtDirC.setText("");
        cmbDirLetra.setSelectedIndex(0);
        txtDirNo1.setText("");
        txtDirNo2.setText("");
        txtEmail.setText("");
        txtDia.setText("DD");
        txtMes.setText("MM");
        txtAño.setText("AAAA");
        cmbCarrera.setSelectedIndex(0);
        txtArchivo.setText("");
        cmbAcceso.setSelectedIndex(0);
        cmbColorLetra.setSelectedIndex(0);
        cmbColorTextField.setSelectedIndex(0);
        cmbIdioma.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        rbMasculino.setSelected(false);
        rbFemenino.setSelected(false);
        rbOtro.setSelected(false);
    }
    private void cmdResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetarActionPerformed
        resetear();
    }//GEN-LAST:event_cmdResetarActionPerformed

    private void cmdAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAlmacenarActionPerformed
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite un codigo!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCodigo.requestFocusInWindow();
        } else if (txtPrimerNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Primer Nombre!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtPrimerNombre.requestFocusInWindow();
        } else if (txtSegundoNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Segundo Nombre!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSegundoNombre.requestFocusInWindow();
        } else if (txtPrimerApellido.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Primer Apellido!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtPrimerApellido.requestFocusInWindow();
        } else if (txtSegundoApellido.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Segundo Apellido!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSegundoApellido.requestFocusInWindow();
        } else if (txtDirC.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite la Dirección!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDirC.requestFocusInWindow();
        } else if (txtDirNo1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Número de la Dirección!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDirNo1.requestFocusInWindow();
        } else if (txtDirNo2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Número de la Dirección!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDirNo2.requestFocusInWindow();
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Email!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocusInWindow();
        } else if (txtDia.getText().equals("DD") || txtDia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Dia de Nacimiento!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDia.requestFocusInWindow();
        } else if (txtMes.getText().equals("MM") || txtMes.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Mes de Nacimiento!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMes.requestFocusInWindow();
        } else if (txtAño.getText().equals("AAAA") || txtAño.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el Año de Nacimiento!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtAño.requestFocusInWindow();
        } else if (rbMasculino.isSelected() == false && rbFemenino.isSelected() == false && rbOtro.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "¡Escoja el tipo de Sexo!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (txtArchivo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Digite el nombre del Archivo!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtArchivo.requestFocusInWindow();
        } else {
            int codigo, dirc, dirno1, dirno2, dia, mes, año, ingles, acceso;
            String primernomb, segundonomb, primerape, segundoape, direccion, email, sexo = "", carrera, horario = "", dir, dirl, fechanac, semestre, archivo;

            codigo = Integer.parseInt(txtCodigo.getText());
            primernomb = txtPrimerNombre.getText();
            segundonomb = txtSegundoNombre.getText();
            primerape = txtPrimerApellido.getText();
            segundoape = txtSegundoApellido.getText();
            dirc = Integer.parseInt(txtDirC.getText());
            dir = cmbCalle.getSelectedItem().toString();
            dirl = cmbDirLetra.getSelectedItem().toString();
            dirno1 = Integer.parseInt(txtDirNo1.getText());
            dirno2 = Integer.parseInt(txtDirNo2.getText());
            direccion = dir + " " + dirc + " " + dirl + " No. " + dirno1 + " - " + dirno2;
            email = txtEmail.getText();
            if (rbMasculino.isSelected() == true) {
                sexo = "Masculino";
            }
            if (rbFemenino.isSelected() == true) {
                sexo = "Femenino";
            }
            if (rbOtro.isSelected() == true) {
                sexo = "Otro";
            }
            dia = Integer.parseInt(txtDia.getText());
            mes = Integer.parseInt(txtMes.getText());
            año = Integer.parseInt(txtAño.getText());
            fechanac = dia + "/" + mes + "/" + año;
            carrera = cmbCarrera.getSelectedItem().toString();
            semestre = jSpinner1.getValue().toString();
            ingles = slNivelIng.getValue();
            if (jCheckBox1.isSelected() == true) {
                horario = horario + "Lunes. ";
            }
            if (jCheckBox2.isSelected() == true) {
                horario = horario + "Martes. ";
            }
            if (jCheckBox3.isSelected() == true) {
                horario = horario + "Miercoles. ";
            }
            if (jCheckBox4.isSelected() == true) {
                horario = horario + "Jueves. ";
            }
            if (jCheckBox5.isSelected() == true) {
                horario = horario + "Viernes. ";
            }
            if (jCheckBox6.isSelected() == true) {
                horario = horario + "Sabado. ";
            }
            archivo = txtArchivo.getText();
            acceso = cmbAcceso.getSelectedIndex();

            if (dia > 30) {
                JOptionPane.showMessageDialog(this, "¡Dia de Nacimiento no Valido!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtDia.requestFocusInWindow();
            } else if (mes > 12) {
                JOptionPane.showMessageDialog(this, "¡Mes de Nacimiento no Valido!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtMes.requestFocusInWindow();
            } else if (año < 1950 && año > 2002) {
                JOptionPane.showMessageDialog(this, "¡Año de Nacimiento no Valido!", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtAño.requestFocusInWindow();
            } else {

                Persona p = new Persona(codigo, primernomb, segundonomb, primerape, segundoape, direccion, email, fechanac, sexo, carrera, semestre, ingles, horario);
                String per = (p.getCodigo() + ", " + p.getPrimernomb() + ", " + p.getSegundonomb() + ", " + p.getPrimerape() + ", " + p.getSegundoape() + ", " + p.getDireccion()
                        + ", " + p.getEmail() + ", " + p.getFnacimiento() + ", " + p.getSexo() + ", " + p.getCarrera() + ", " + p.getSemestre() + ", " + p.getNiveling() + ", " + p.getHorario());
                switch (acceso) {
                    case 0:
                        try {
                            FileWriter fichero = new FileWriter("src/datos/" + archivo + ".txt");
                            fichero.write(per);
                            fichero.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                        JOptionPane.showMessageDialog(this, "El registro se realizó correctamente!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                        resetear();
                        break;
                    case 1:
                        try {
                            AccesoAleatorio.crearFileAlumno(new File("src/datos/" + archivo + ".bin"));
                            AccesoAleatorio.añadirPersona(new Persona(codigo, primernomb, segundonomb, primerape, segundoape, direccion, email, fechanac, sexo, carrera, semestre, ingles, horario, true));
                            AccesoAleatorio.cerrar();
                            JOptionPane.showMessageDialog(this, "El registro se realizó correctamente!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                            resetear();
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(this, "Error en la escritura de datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                        break;
                    case 2:

                        Connection cn = null;
                        PreparedStatement preparedStmt = null;
                        try {
                            cn = new Conexion().obtenerConexion();
                            String sql;
                            sql = "insert into person(codigo,primernomb,segundonomb,primerape,segundoape,direccion,email,fechanac,sexo,carrera,semestre,ingles,horario) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                            preparedStmt = cn.prepareStatement(sql);
                            preparedStmt.setInt(1, codigo);
                            preparedStmt.setString(2, primernomb);
                            preparedStmt.setString(3, segundonomb);
                            preparedStmt.setString(4, primerape);
                            preparedStmt.setString(5, segundoape);
                            preparedStmt.setString(6, direccion);
                            preparedStmt.setString(7, email);
                            preparedStmt.setString(8, fechanac);
                            preparedStmt.setString(9, sexo);
                            preparedStmt.setString(10, carrera);
                            preparedStmt.setString(11, semestre);
                            preparedStmt.setInt(12, ingles);
                            preparedStmt.setString(13, horario);
                            preparedStmt.execute();
                            cn.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(this, "El registro se realizó correctamente!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                        resetear();
                        break;
                }

            }
        }
    }//GEN-LAST:event_cmdAlmacenarActionPerformed

    private void cmdEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEstablecerActionPerformed
        int opl, opt, idioma;
        opl = cmbColorLetra.getSelectedIndex();
        opt = cmbColorTextField.getSelectedIndex();
        idioma = cmbIdioma.getSelectedIndex();
        switch (opl) {
            case 0:
                this.lbCodigo.setForeground(Color.black);
                this.lbPrimernomb.setForeground(Color.black);
                this.lbSegundonomb.setForeground(Color.black);
                this.lbPrimerape.setForeground(Color.black);
                this.lbSegundoape.setForeground(Color.black);
                this.lbDireccion.setForeground(Color.black);
                this.lbEmail.setForeground(Color.black);
                this.lbFecha.setForeground(Color.black);
                this.lbSexo.setForeground(Color.black);
                this.lbCarrera.setForeground(Color.black);
                this.lbSemestre.setForeground(Color.black);
                this.lbIngles.setForeground(Color.black);
                this.lbHorario.setForeground(Color.black);
                this.lbArchivo.setForeground(Color.black);
                this.lbAcceso.setForeground(Color.black);
                this.lbLookandfeel.setForeground(Color.black);
                this.lbCletra.setForeground(Color.black);
                this.lbCtextfield.setForeground(Color.black);
                this.lbIdioma.setForeground(Color.black);
                this.lbDatosPersonales.setForeground(Color.black);
                this.lbDatosAcademicos.setForeground(Color.black);
                this.lbParametros.setForeground(Color.black);
                break;
            case 1:
                this.lbCodigo.setForeground(Color.yellow);
                this.lbPrimernomb.setForeground(Color.yellow);
                this.lbSegundonomb.setForeground(Color.yellow);
                this.lbPrimerape.setForeground(Color.yellow);
                this.lbSegundoape.setForeground(Color.yellow);
                this.lbDireccion.setForeground(Color.yellow);
                this.lbEmail.setForeground(Color.yellow);
                this.lbFecha.setForeground(Color.yellow);
                this.lbSexo.setForeground(Color.yellow);
                this.lbCarrera.setForeground(Color.yellow);
                this.lbSemestre.setForeground(Color.yellow);
                this.lbIngles.setForeground(Color.yellow);
                this.lbHorario.setForeground(Color.yellow);
                this.lbArchivo.setForeground(Color.yellow);
                this.lbAcceso.setForeground(Color.yellow);
                this.lbLookandfeel.setForeground(Color.yellow);
                this.lbCletra.setForeground(Color.yellow);
                this.lbCtextfield.setForeground(Color.yellow);
                this.lbIdioma.setForeground(Color.yellow);
                this.lbDatosAcademicos.setForeground(Color.yellow);
                this.lbDatosPersonales.setForeground(Color.yellow);
                this.lbParametros.setForeground(Color.yellow);
                break;
            case 2:
                this.lbCodigo.setForeground(Color.blue);
                this.lbPrimernomb.setForeground(Color.blue);
                this.lbSegundonomb.setForeground(Color.blue);
                this.lbPrimerape.setForeground(Color.blue);
                this.lbSegundoape.setForeground(Color.blue);
                this.lbDireccion.setForeground(Color.blue);
                this.lbEmail.setForeground(Color.blue);
                this.lbFecha.setForeground(Color.blue);
                this.lbSexo.setForeground(Color.blue);
                this.lbCarrera.setForeground(Color.blue);
                this.lbSemestre.setForeground(Color.blue);
                this.lbIngles.setForeground(Color.blue);
                this.lbHorario.setForeground(Color.blue);
                this.lbArchivo.setForeground(Color.blue);
                this.lbAcceso.setForeground(Color.blue);
                this.lbLookandfeel.setForeground(Color.blue);
                this.lbCletra.setForeground(Color.blue);
                this.lbCtextfield.setForeground(Color.blue);
                this.lbIdioma.setForeground(Color.blue);
                this.lbDatosPersonales.setForeground(Color.blue);
                this.lbDatosAcademicos.setForeground(Color.blue);
                this.lbParametros.setForeground(Color.blue);
                break;
            case 3:
                this.lbCodigo.setForeground(Color.red);
                this.lbPrimernomb.setForeground(Color.red);
                this.lbSegundonomb.setForeground(Color.red);
                this.lbPrimerape.setForeground(Color.red);
                this.lbSegundoape.setForeground(Color.red);
                this.lbDireccion.setForeground(Color.red);
                this.lbEmail.setForeground(Color.red);
                this.lbFecha.setForeground(Color.red);
                this.lbSexo.setForeground(Color.red);
                this.lbCarrera.setForeground(Color.red);
                this.lbSemestre.setForeground(Color.red);
                this.lbIngles.setForeground(Color.red);
                this.lbHorario.setForeground(Color.red);
                this.lbArchivo.setForeground(Color.red);
                this.lbAcceso.setForeground(Color.red);
                this.lbLookandfeel.setForeground(Color.red);
                this.lbCletra.setForeground(Color.red);
                this.lbCtextfield.setForeground(Color.red);
                this.lbIdioma.setForeground(Color.red);
                this.lbDatosPersonales.setForeground(Color.red);
                this.lbDatosAcademicos.setForeground(Color.red);
                this.lbParametros.setForeground(Color.red);
                break;
            case 4:
                this.lbCodigo.setForeground(Color.pink);
                this.lbPrimernomb.setForeground(Color.pink);
                this.lbSegundonomb.setForeground(Color.pink);
                this.lbPrimerape.setForeground(Color.pink);
                this.lbSegundoape.setForeground(Color.pink);
                this.lbDireccion.setForeground(Color.pink);
                this.lbEmail.setForeground(Color.pink);
                this.lbFecha.setForeground(Color.pink);
                this.lbSexo.setForeground(Color.pink);
                this.lbCarrera.setForeground(Color.pink);
                this.lbSemestre.setForeground(Color.pink);
                this.lbIngles.setForeground(Color.pink);
                this.lbHorario.setForeground(Color.pink);
                this.lbArchivo.setForeground(Color.pink);
                this.lbAcceso.setForeground(Color.pink);
                this.lbLookandfeel.setForeground(Color.pink);
                this.lbCletra.setForeground(Color.pink);
                this.lbCtextfield.setForeground(Color.pink);
                this.lbIdioma.setForeground(Color.pink);
                this.lbDatosPersonales.setForeground(Color.pink);
                this.lbDatosAcademicos.setForeground(Color.pink);
                this.lbParametros.setForeground(Color.pink);
                break;
            case 5:
                this.lbCodigo.setForeground(Color.green);
                this.lbPrimernomb.setForeground(Color.green);
                this.lbSegundonomb.setForeground(Color.green);
                this.lbPrimerape.setForeground(Color.green);
                this.lbSegundoape.setForeground(Color.green);
                this.lbDireccion.setForeground(Color.green);
                this.lbEmail.setForeground(Color.green);
                this.lbFecha.setForeground(Color.green);
                this.lbSexo.setForeground(Color.green);
                this.lbCarrera.setForeground(Color.green);
                this.lbSemestre.setForeground(Color.green);
                this.lbIngles.setForeground(Color.green);
                this.lbHorario.setForeground(Color.green);
                this.lbArchivo.setForeground(Color.green);
                this.lbAcceso.setForeground(Color.green);
                this.lbLookandfeel.setForeground(Color.green);
                this.lbCletra.setForeground(Color.green);
                this.lbCtextfield.setForeground(Color.green);
                this.lbIdioma.setForeground(Color.green);
                this.lbDatosPersonales.setForeground(Color.green);
                this.lbDatosAcademicos.setForeground(Color.green);
                this.lbParametros.setForeground(Color.green);
                break;
            case 6:
                this.lbCodigo.setForeground(Color.orange);
                this.lbPrimernomb.setForeground(Color.orange);
                this.lbSegundonomb.setForeground(Color.orange);
                this.lbPrimerape.setForeground(Color.orange);
                this.lbSegundoape.setForeground(Color.orange);
                this.lbDireccion.setForeground(Color.orange);
                this.lbEmail.setForeground(Color.orange);
                this.lbFecha.setForeground(Color.orange);
                this.lbSexo.setForeground(Color.orange);
                this.lbCarrera.setForeground(Color.orange);
                this.lbSemestre.setForeground(Color.orange);
                this.lbIngles.setForeground(Color.orange);
                this.lbHorario.setForeground(Color.orange);
                this.lbArchivo.setForeground(Color.orange);
                this.lbAcceso.setForeground(Color.orange);
                this.lbLookandfeel.setForeground(Color.orange);
                this.lbCletra.setForeground(Color.orange);
                this.lbCtextfield.setForeground(Color.orange);
                this.lbIdioma.setForeground(Color.orange);
                this.lbDatosPersonales.setForeground(Color.orange);
                this.lbDatosAcademicos.setForeground(Color.orange);
                this.lbParametros.setForeground(Color.orange);
                break;
            case 7:
                this.lbCodigo.setForeground(Color.white);
                this.lbPrimernomb.setForeground(Color.white);
                this.lbSegundonomb.setForeground(Color.white);
                this.lbPrimerape.setForeground(Color.white);
                this.lbSegundoape.setForeground(Color.white);
                this.lbDireccion.setForeground(Color.white);
                this.lbEmail.setForeground(Color.white);
                this.lbFecha.setForeground(Color.white);
                this.lbSexo.setForeground(Color.white);
                this.lbCarrera.setForeground(Color.white);
                this.lbSemestre.setForeground(Color.white);
                this.lbIngles.setForeground(Color.white);
                this.lbHorario.setForeground(Color.white);
                this.lbArchivo.setForeground(Color.white);
                this.lbAcceso.setForeground(Color.white);
                this.lbLookandfeel.setForeground(Color.white);
                this.lbCletra.setForeground(Color.white);
                this.lbCtextfield.setForeground(Color.white);
                this.lbIdioma.setForeground(Color.white);
                this.lbDatosPersonales.setForeground(Color.white);
                this.lbDatosAcademicos.setForeground(Color.white);
                this.lbParametros.setForeground(Color.white);
                break;

        }
        switch (opt) {
            case 0:
                this.txtCodigo.setBackground(Color.black);
                this.txtPrimerNombre.setBackground(Color.black);
                this.txtSegundoNombre.setBackground(Color.black);
                this.txtPrimerApellido.setBackground(Color.black);
                this.txtSegundoApellido.setBackground(Color.black);
                this.txtDirC.setBackground(Color.black);
                this.txtDirNo1.setBackground(Color.black);
                this.txtDirNo2.setBackground(Color.black);
                this.txtEmail.setBackground(Color.black);
                this.txtDia.setBackground(Color.black);
                this.txtMes.setBackground(Color.black);
                this.txtAño.setBackground(Color.black);
                this.txtArchivo.setBackground(Color.black);
                break;
            case 1:
                this.txtCodigo.setBackground(Color.yellow);
                this.txtPrimerNombre.setBackground(Color.yellow);
                this.txtSegundoNombre.setBackground(Color.yellow);
                this.txtPrimerApellido.setBackground(Color.yellow);
                this.txtSegundoApellido.setBackground(Color.yellow);
                this.txtDirC.setBackground(Color.yellow);
                this.txtDirNo1.setBackground(Color.yellow);
                this.txtDirNo2.setBackground(Color.yellow);
                this.txtEmail.setBackground(Color.yellow);
                this.txtDia.setBackground(Color.yellow);
                this.txtMes.setBackground(Color.yellow);
                this.txtAño.setBackground(Color.yellow);
                this.txtArchivo.setBackground(Color.yellow);
                break;
            case 2:
                this.txtCodigo.setBackground(Color.blue);
                this.txtPrimerNombre.setBackground(Color.blue);
                this.txtSegundoNombre.setBackground(Color.blue);
                this.txtPrimerApellido.setBackground(Color.blue);
                this.txtSegundoApellido.setBackground(Color.blue);
                this.txtDirC.setBackground(Color.blue);
                this.txtDirNo1.setBackground(Color.blue);
                this.txtDirNo2.setBackground(Color.blue);
                this.txtEmail.setBackground(Color.blue);
                this.txtDia.setBackground(Color.blue);
                this.txtMes.setBackground(Color.blue);
                this.txtAño.setBackground(Color.blue);
                this.txtArchivo.setBackground(Color.blue);
                break;
            case 3:
                this.txtCodigo.setBackground(Color.red);
                this.txtPrimerNombre.setBackground(Color.red);
                this.txtSegundoNombre.setBackground(Color.red);
                this.txtPrimerApellido.setBackground(Color.red);
                this.txtSegundoApellido.setBackground(Color.red);
                this.txtDirC.setBackground(Color.red);
                this.txtDirNo1.setBackground(Color.red);
                this.txtDirNo2.setBackground(Color.red);
                this.txtEmail.setBackground(Color.red);
                this.txtDia.setBackground(Color.red);
                this.txtMes.setBackground(Color.red);
                this.txtAño.setBackground(Color.red);
                this.txtArchivo.setBackground(Color.red);
                break;
            case 4:
                this.txtCodigo.setBackground(Color.pink);
                this.txtPrimerNombre.setBackground(Color.pink);
                this.txtSegundoNombre.setBackground(Color.pink);
                this.txtPrimerApellido.setBackground(Color.pink);
                this.txtSegundoApellido.setBackground(Color.pink);
                this.txtDirC.setBackground(Color.pink);
                this.txtDirNo1.setBackground(Color.pink);
                this.txtDirNo2.setBackground(Color.pink);
                this.txtEmail.setBackground(Color.pink);
                this.txtDia.setBackground(Color.pink);
                this.txtMes.setBackground(Color.pink);
                this.txtAño.setBackground(Color.pink);
                this.txtArchivo.setBackground(Color.pink);
                break;
            case 5:
                this.txtCodigo.setBackground(Color.green);
                this.txtPrimerNombre.setBackground(Color.green);
                this.txtSegundoNombre.setBackground(Color.green);
                this.txtPrimerApellido.setBackground(Color.green);
                this.txtSegundoApellido.setBackground(Color.green);
                this.txtDirC.setBackground(Color.green);
                this.txtDirNo1.setBackground(Color.green);
                this.txtDirNo2.setBackground(Color.green);
                this.txtEmail.setBackground(Color.green);
                this.txtDia.setBackground(Color.green);
                this.txtMes.setBackground(Color.green);
                this.txtAño.setBackground(Color.green);
                this.txtArchivo.setBackground(Color.green);
                break;
            case 6:
                this.txtCodigo.setBackground(Color.orange);
                this.txtPrimerNombre.setBackground(Color.orange);
                this.txtSegundoNombre.setBackground(Color.orange);
                this.txtPrimerApellido.setBackground(Color.orange);
                this.txtSegundoApellido.setBackground(Color.orange);
                this.txtDirC.setBackground(Color.orange);
                this.txtDirNo1.setBackground(Color.orange);
                this.txtDirNo2.setBackground(Color.orange);
                this.txtEmail.setBackground(Color.orange);
                this.txtDia.setBackground(Color.orange);
                this.txtMes.setBackground(Color.orange);
                this.txtAño.setBackground(Color.orange);
                this.txtArchivo.setBackground(Color.orange);
                break;
            case 7:
                this.txtCodigo.setBackground(Color.white);
                this.txtPrimerNombre.setBackground(Color.white);
                this.txtSegundoNombre.setBackground(Color.white);
                this.txtPrimerApellido.setBackground(Color.white);
                this.txtSegundoApellido.setBackground(Color.white);
                this.txtDirC.setBackground(Color.white);
                this.txtDirNo1.setBackground(Color.white);
                this.txtDirNo2.setBackground(Color.white);
                this.txtEmail.setBackground(Color.white);
                this.txtDia.setBackground(Color.white);
                this.txtMes.setBackground(Color.white);
                this.txtAño.setBackground(Color.white);
                this.txtArchivo.setBackground(Color.white);
                break;
        }

        JLabel label[] = {lbTitulo, lbCodigo, lbPrimernomb, lbSegundonomb, lbPrimerape, lbSegundoape, lbDireccion, lbEmail, lbFecha, lbSexo,
            lbCarrera, lbSemestre, lbIngles, lbHorario, lbArchivo, lbAcceso, lbCletra, lbCtextfield, lbIdioma, lbDatosPersonales, lbDatosAcademicos, lbParametros};
        JButton boton[] = {cmdAlmacenar, cmdCancelar, cmdResetar, cmdEstablecer, cmdVerPersonas};
        JRadioButton radio[] = {rbMasculino, rbFemenino, rbOtro};
        JCheckBox check[] = {jCheckBox1, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6};

        switch (idioma) {
            case 0:
                Idioma.español(label, boton, check, radio);
                break;
            case 1:
                Idioma.ingles(label, boton, check, radio);
                break;
        }
    }//GEN-LAST:event_cmdEstablecerActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtPrimerNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerNombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrimerNombreKeyTyped

    private void txtSegundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoNombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSegundoNombreKeyTyped

    private void txtPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrimerApellidoKeyTyped

    private void txtSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSegundoApellidoKeyTyped

    private void txtDirCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirCKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDirCKeyTyped

    private void txtDirNo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirNo1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDirNo1KeyTyped

    private void txtDirNo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirNo2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDirNo2KeyTyped

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAñoKeyTyped

    private void txtDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMouseClicked
        txtDia.setText("");
    }//GEN-LAST:event_txtDiaMouseClicked

    private void txtMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesMouseClicked
        txtMes.setText("");
    }//GEN-LAST:event_txtMesMouseClicked

    private void txtAñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAñoMouseClicked
        txtAño.setText("");
    }//GEN-LAST:event_txtAñoMouseClicked
    public boolean isEmail(String email) {
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_\\+])*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(email);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }
    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (isEmail(txtEmail.getText())) {

        } else if (txtEmail.getText().trim().isEmpty()) {

        } else {
            JOptionPane.showMessageDialog(this, "¡Email no Valido!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void cmdVerPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerPersonasActionPerformed
        int acceso = cmbAcceso.getSelectedIndex();
        switch (acceso) {
            case 0:
                if (txtArchivo.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Digite el nombre del archivo a ver!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtArchivo.requestFocusInWindow();
                } else {
                    String archivo = txtArchivo.getText();
                    String e = "";
                    try {
                        FileReader entrada = new FileReader("src/datos/" + archivo + ".txt");
                        BufferedReader br = new BufferedReader(entrada);
                        String s;
                        while ((s = br.readLine()) != null) {
                            e = s;
                        }
                        JOptionPane.showMessageDialog(this, e);
                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error en la búsqueda de registros!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case 1:
                if (txtArchivo.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Digite el primer nombre de la persona a ver!", "ERROR", JOptionPane.WARNING_MESSAGE);
                    txtArchivo.requestFocusInWindow();
                } else {
                    String archivo = txtArchivo.getText();
                    try {
                        AccesoAleatorio.crearFileAlumno(new File("src/datos/" + archivo + ".bin"));
                        int i = AccesoAleatorio.buscarRegistro(archivo);
                        if (i == -1) {
                            JOptionPane.showMessageDialog(this, "Ningún registro coincide con los datos de búsqueda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        JOptionPane.showMessageDialog(this, AccesoAleatorio.getPersona(i));
                        AccesoAleatorio.cerrar();
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(this, "Error en la búsqueda de registros!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                break;

            case 2:
                JOptionPane.showMessageDialog(this, "Busqueda No disponible", "ERROR", JOptionPane.ERROR_MESSAGE);
                break;
        }


    }//GEN-LAST:event_cmdVerPersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAcceso;
    private javax.swing.JComboBox<String> cmbCalle;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbColorLetra;
    private javax.swing.JComboBox<String> cmbColorTextField;
    private javax.swing.JComboBox<String> cmbDirLetra;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JButton cmdAlmacenar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEstablecer;
    private javax.swing.JButton cmdResetar;
    private javax.swing.JButton cmdVerPersonas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbAcceso;
    private javax.swing.JLabel lbArchivo;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCletra;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCtextfield;
    private javax.swing.JLabel lbDatosAcademicos;
    private javax.swing.JLabel lbDatosPersonales;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHorario;
    private javax.swing.JLabel lbIdioma;
    private javax.swing.JLabel lbIngles;
    private javax.swing.JLabel lbLookandfeel;
    private javax.swing.JLabel lbParametros;
    private javax.swing.JLabel lbPrimerape;
    private javax.swing.JLabel lbPrimernomb;
    private javax.swing.JLabel lbSegundoape;
    private javax.swing.JLabel lbSegundonomb;
    private javax.swing.JLabel lbSemestre;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.ButtonGroup rbSexo;
    private javax.swing.JSlider slNivelIng;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDirC;
    private javax.swing.JTextField txtDirNo1;
    private javax.swing.JTextField txtDirNo2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
